import { CgWebsite } from 'react-icons/cg';
import { FaFacebook, FaGithub, FaJava, FaLinkedin } from 'react-icons/fa6';
import {
  LuChevronLeft,
  LuChevronRight,
  LuDownload,
  LuFileText,
  LuImage,
  LuLanguages,
  LuLink,
  LuMenu,
  LuMoon,
  LuPaintbrush,
  LuPrinter,
  LuSun,
  LuUser,
  LuX,
} from 'react-icons/lu';
import {
  PiAndroidLogoBold,
  PiCertificate,
  PiCodeBlock,
  PiDevices,
  PiDotOutlineFill,
  PiStudent,
} from 'react-icons/pi';
import {
  RiExpandUpDownFill,
  RiFileTextLine,
  RiLoader5Line,
  RiQuillPenLine,
  RiWhatsappLine,
} from 'react-icons/ri';
import {
  SiAmazon,
  SiAndroidstudio,
  SiApachecordova,
  SiBootstrap,
  SiClojure,
  SiCss3,
  SiCypress,
  SiDocker,
  SiElectron,
  SiExpo,
  SiExpress,
  SiFigma,
  SiGit,
  SiHeroku,
  SiHtml5,
  SiInsomnia,
  SiJavascript,
  SiJest,
  SiMantine,
  SiMaterialdesign,
  SiMongodb,
  SiNestjs,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiPostman,
  SiPuppeteer,
  SiReact,
  SiSass,
  SiSelenium,
  SiShadcnui,
  SiSpringboot,
  SiStyledcomponents,
  SiSvelte,
  SiTailwindcss,
  SiTypescript,
  SiUdemy,
} from 'react-icons/si';

export type IconsType = keyof typeof iconMap;

export const iconMap = {
  download: <LuDownload />,
  selector: <RiExpandUpDownFill />,
  spinner: <RiLoader5Line />,
  github: <FaGithub />,
  template: <RiFileTextLine />,
  language: <LuLanguages />,
  link: <LuLink />,
  textDocument: <LuFileText />,
  image: <LuImage />,
  user: <LuUser />,
  theme: <LuPaintbrush />,
  sun: <LuSun />,
  moon: <LuMoon />,
  website: <CgWebsite />,
  menu: <LuMenu />,
  close: <LuX />,
  linkedin: <FaLinkedin />,
  facebook: <FaFacebook />,
  html: <SiHtml5 />,
  css: <SiCss3 />,
  javascript: <SiJavascript />,
  typescript: <SiTypescript />,
  docker: <SiDocker />,
  styledComponents: <SiStyledcomponents />,
  aws: <SiAmazon />,
  mongoDb: <SiMongodb />,
  nodejs: <SiNodedotjs />,
  sass: <SiSass />,
  springBoot: <SiSpringboot />,
  svelte: <SiSvelte />,
  tailwind: <SiTailwindcss />,
  java: <FaJava />,
  react: <SiReact />,
  jest: <SiJest />,
  postgres: <SiPostgresql />,
  puppeter: <SiPuppeteer />,
  selenium: <SiSelenium />,
  expressJS: <SiExpress />,
  nestJS: <SiNestjs />,
  nextJS: <SiNextdotjs />,
  mantineui: <SiMantine />,
  materialui: <SiMaterialdesign />,
  clojure: <SiClojure />,
  expo: <SiExpo />,
  electron: <SiElectron />,
  figma: <SiFigma />,
  git: <SiGit />,
  androidStudio: <SiAndroidstudio />,
  insomnia: <SiInsomnia />,
  postman: <SiPostman />,
  heroku: <SiHeroku />,
  bootstrap: <SiBootstrap />,
  whatsapp: <RiWhatsappLine />,
  udemy: <SiUdemy />,
  school: <PiStudent />,
  certificates: <PiCertificate />,
  caretLeft: <LuChevronLeft />,
  caretRight: <LuChevronRight />,
  projects: <PiDevices />,
  cordova: <SiApachecordova />,
  cypress: <SiCypress />,
  pritter: <LuPrinter />,
  quill: <RiQuillPenLine />,
  shadcn: <SiShadcnui />,
  android: <PiAndroidLogoBold />,
  codeBlock: <PiCodeBlock />,
  dot: <PiDotOutlineFill />,
};
