import { CgWebsite } from 'react-icons/cg';
import { FaFacebook, FaGithub, FaJava, FaLinkedin } from 'react-icons/fa6';
import {
  LuDownload,
  LuFileText,
  LuImage,
  LuLanguages,
  LuLink,
  LuMenu,
  LuMoon,
  LuPaintbrush,
  LuSun,
  LuUser,
  LuX,
} from 'react-icons/lu';
import { RiExpandUpDownFill, RiFileTextLine, RiLoader2Fill } from 'react-icons/ri';
import {
  SiAmazonaws,
  SiCss3,
  SiDocker,
  SiExpress,
  SiHtml5,
  SiJavascript,
  SiJest,
  SiMongodb,
  SiNestjs,
  SiNextui,
  SiNodedotjs,
  SiPostgresql,
  SiPuppeteer,
  SiReact,
  SiSass,
  SiSelenium,
  SiSpringboot,
  SiStyledcomponents,
  SiSvelte,
  SiTailwindcss,
  SiTypescript,
} from 'react-icons/si';

export const iconMap: Record<Props.Icons['type'], React.ReactElement> = {
  download: <LuDownload />,
  selector: <RiExpandUpDownFill />,
  spinner: <RiLoader2Fill />,
  github: <FaGithub />,
  template: <RiFileTextLine />,
  language: <LuLanguages />,
  link: <LuLink />,
  textDocument: <LuFileText />,
  image: <LuImage />,
  user: <LuUser />,
  theme: <LuPaintbrush />,
  sun: <LuSun />,
  moon: <LuMoon />,
  website: <CgWebsite />,
  menu: <LuMenu />,
  close: <LuX />,
  linkedin: <FaLinkedin />,
  facebook: <FaFacebook />,
  html: <SiHtml5 />,
  css: <SiCss3 />,
  javascript: <SiJavascript />,
  typescript: <SiTypescript />,
  docker: <SiDocker />,
  styledComponents: <SiStyledcomponents />,
  aws: <SiAmazonaws />,
  mongoDb: <SiMongodb />,
  nodejs: <SiNodedotjs />,
  sass: <SiSass />,
  springBoot: <SiSpringboot />,
  svelte: <SiSvelte />,
  tailwind: <SiTailwindcss />,
  java: <FaJava />,
  react: <SiReact />,
  jest: <SiJest />,
  postgres: <SiPostgresql />,
  puppeter: <SiPuppeteer />,
  selenium: <SiSelenium />,
  expressJS: <SiExpress />,
  nestJS: <SiNestjs />,
  nextJS: <SiNextui />,
};
